---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    [Global]
    identity-endpoint=https://{Identity Endpoint}/v3.0
    ecs-endpoint=https://{ECS endpoint}
    as-endpoint=https://{AS endpoint}
    project-id={Project ID}
    access-key={Access Key}
    secret-key={Secret Key}
    cloud=myhuaweicloud.com
    region={Region}
    domain-id={Domain ID}
